// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgzoUb3WC4wvasQFFrTX2_SeenKafv2Tg',
    appId: '1:521096612958:web:ca38a5dfacb0d0e8c1b8cf',
    messagingSenderId: '521096612958',
    projectId: 'chat-app-cdc69',
    authDomain: 'chat-app-cdc69.firebaseapp.com',
    storageBucket: 'chat-app-cdc69.appspot.com',
    measurementId: 'G-EHQ2CXDX7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAFIx0oSdclnrXsn3uu-P0xki-0Wrt860',
    appId: '1:521096612958:android:5373972cfaf82253c1b8cf',
    messagingSenderId: '521096612958',
    projectId: 'chat-app-cdc69',
    storageBucket: 'chat-app-cdc69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-qILBjAZmYplV_dMVKhtRuIYpdyyCKJg',
    appId: '1:521096612958:ios:671a9264b90f95cac1b8cf',
    messagingSenderId: '521096612958',
    projectId: 'chat-app-cdc69',
    storageBucket: 'chat-app-cdc69.appspot.com',
    iosBundleId: 'com.example.nullProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-qILBjAZmYplV_dMVKhtRuIYpdyyCKJg',
    appId: '1:521096612958:ios:671a9264b90f95cac1b8cf',
    messagingSenderId: '521096612958',
    projectId: 'chat-app-cdc69',
    storageBucket: 'chat-app-cdc69.appspot.com',
    iosBundleId: 'com.example.nullProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgzoUb3WC4wvasQFFrTX2_SeenKafv2Tg',
    appId: '1:521096612958:web:df6ada058b79e8d0c1b8cf',
    messagingSenderId: '521096612958',
    projectId: 'chat-app-cdc69',
    authDomain: 'chat-app-cdc69.firebaseapp.com',
    storageBucket: 'chat-app-cdc69.appspot.com',
    measurementId: 'G-4ST5GKP71L',
  );
}
